# you would want to change this
baseURL = "https://starless.ruiny.de/"
locale = "en-us"
title = "starless"
theme = "starless"
enableRobotsTXT = true
disableHugoGeneratorInject = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.highlight]
style = "gruvbox"

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [["$$", "$$"]]
inline = [["\\(", "\\)"]]

[params]
description = "Starless is a small Hugo theme for dark, text first sites."
sidebarFooter = "built with Hugo"
homeFooter = "see you in another file!"
