# you would want to change this
baseURL = "https://starless.ruiny.de/"
locale = "en-us"
title = "starless"
enableRobotsTXT = true
disableHugoGeneratorInject = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.highlight]
style = "gruvbox"

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [["$$", "$$"]]
inline = [["\\(", "\\)"]]

[params]
description = "Starless is a minimal hugo theme for seldom updated blogs"
sidebarFooter = "built with Hugo"
homeFooter = "see you in another file!"

[module]
[[module.imports]]
path = "github.com/ruinivist/hugo-starless"
